class Autogenerated {
  ErrorMessage errorMessage;
  List<RealtimeArrivalList> realtimeArrivalList;

  Autogenerated({this.errorMessage, this.realtimeArrivalList});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    errorMessage = json['errorMessage'] != null
        ? new ErrorMessage.fromJson(json['errorMessage'])
        : null;
    if (json['realtimeArrivalList'] != null) {
      // ignore: deprecated_member_use
      realtimeArrivalList = new List<RealtimeArrivalList>();
      json['realtimeArrivalList'].forEach((v) {
        realtimeArrivalList.add(new RealtimeArrivalList.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.errorMessage != null) {
      data['errorMessage'] = this.errorMessage.toJson();
    }
    if (this.realtimeArrivalList != null) {
      data['realtimeArrivalList'] =
          this.realtimeArrivalList.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ErrorMessage {
  int status;
  String code;
  String message;
  String link;
  String developerMessage;
  int total;

  ErrorMessage(
      {this.status,
        this.code,
        this.message,
        this.link,
        this.developerMessage,
        this.total});

  ErrorMessage.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code'];
    message = json['message'];
    link = json['link'];
    developerMessage = json['developerMessage'];
    total = json['total'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['code'] = this.code;
    data['message'] = this.message;
    data['link'] = this.link;
    data['developerMessage'] = this.developerMessage;
    data['total'] = this.total;
    return data;
  }
}

class RealtimeArrivalList {
  Null beginRow;
  Null endRow;
  Null curPage;
  Null pageRow;
  int totalCount;
  int rowNum;
  int selectedCount;
  String subwayId;
  Null subwayNm;
  String updnLine;
  String trainLineNm;
  String subwayHeading;
  String statnFid;
  String statnTid;
  String statnId;
  String statnNm;
  Null trainCo;
  String ordkey;
  String subwayList;
  String statnList;
  String btrainSttus;
  String barvlDt;
  String btrainNo;
  String bstatnId;
  String bstatnNm;
  String recptnDt;
  String arvlMsg2;
  String arvlMsg3;
  String arvlCd;

  RealtimeArrivalList(
      {this.beginRow,
        this.endRow,
        this.curPage,
        this.pageRow,
        this.totalCount,
        this.rowNum,
        this.selectedCount,
        this.subwayId,
        this.subwayNm,
        this.updnLine,
        this.trainLineNm,
        this.subwayHeading,
        this.statnFid,
        this.statnTid,
        this.statnId,
        this.statnNm,
        this.trainCo,
        this.ordkey,
        this.subwayList,
        this.statnList,
        this.btrainSttus,
        this.barvlDt,
        this.btrainNo,
        this.bstatnId,
        this.bstatnNm,
        this.recptnDt,
        this.arvlMsg2,
        this.arvlMsg3,
        this.arvlCd});

  RealtimeArrivalList.fromJson(Map<String, dynamic> json) {
    beginRow = json['beginRow'];
    endRow = json['endRow'];
    curPage = json['curPage'];
    pageRow = json['pageRow'];
    totalCount = json['totalCount'];
    rowNum = json['rowNum'];
    selectedCount = json['selectedCount'];
    subwayId = json['subwayId'];
    subwayNm = json['subwayNm'];
    updnLine = json['updnLine'];
    trainLineNm = json['trainLineNm'];
    subwayHeading = json['subwayHeading'];
    statnFid = json['statnFid'];
    statnTid = json['statnTid'];
    statnId = json['statnId'];
    statnNm = json['statnNm'];
    trainCo = json['trainCo'];
    ordkey = json['ordkey'];
    subwayList = json['subwayList'];
    statnList = json['statnList'];
    btrainSttus = json['btrainSttus'];
    barvlDt = json['barvlDt'];
    btrainNo = json['btrainNo'];
    bstatnId = json['bstatnId'];
    bstatnNm = json['bstatnNm'];
    recptnDt = json['recptnDt'];
    arvlMsg2 = json['arvlMsg2'];
    arvlMsg3 = json['arvlMsg3'];
    arvlCd = json['arvlCd'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['beginRow'] = this.beginRow;
    data['endRow'] = this.endRow;
    data['curPage'] = this.curPage;
    data['pageRow'] = this.pageRow;
    data['totalCount'] = this.totalCount;
    data['rowNum'] = this.rowNum;
    data['selectedCount'] = this.selectedCount;
    data['subwayId'] = this.subwayId;
    data['subwayNm'] = this.subwayNm;
    data['updnLine'] = this.updnLine;
    data['trainLineNm'] = this.trainLineNm;
    data['subwayHeading'] = this.subwayHeading;
    data['statnFid'] = this.statnFid;
    data['statnTid'] = this.statnTid;
    data['statnId'] = this.statnId;
    data['statnNm'] = this.statnNm;
    data['trainCo'] = this.trainCo;
    data['ordkey'] = this.ordkey;
    data['subwayList'] = this.subwayList;
    data['statnList'] = this.statnList;
    data['btrainSttus'] = this.btrainSttus;
    data['barvlDt'] = this.barvlDt;
    data['btrainNo'] = this.btrainNo;
    data['bstatnId'] = this.bstatnId;
    data['bstatnNm'] = this.bstatnNm;
    data['recptnDt'] = this.recptnDt;
    data['arvlMsg2'] = this.arvlMsg2;
    data['arvlMsg3'] = this.arvlMsg3;
    data['arvlCd'] = this.arvlCd;
    return data;
  }
}
